FROM ubuntu/apache2

WORKDIR /

EXPOSE 80 443

#Definir timezone pra não travar no apt update
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
#Instalar dependencias do Syspass
RUN apt update && apt install software-properties-common -y
RUN add-apt-repository ppa:ondrej/php
RUN apt install -y locales unzip wget git libapache2-mod-php7.3 php-pear php7.3 php7.3-cgi php7.3-cli php7.3-common php7.3-fpm php7.3-gd php7.3-json php7.3-mysql php7.3-readline php7.3 curl php7.3-intl php7.3-ldap php7.3-mcrypt php7.3-xml php7.3-mbstring
#Permissões/criação de diretorio
RUN mkdir /var/www/html/syspass
RUN git clone https://github.com/nuxsmin/sysPass.git  /var/www/html/syspass
RUN chown www-data -R /var/www/html/syspass
#Copiar meus arquivos do syspass
#COPY /syspass/app/config/config.xml /var/www/html/syspass/app/config
RUN chmod 750 /var/www/html/syspass/app/config /var/www/html/syspass/app/backup
#Dependencias do php com composer
COPY install_composer.sh /var/www/html/syspass
RUN chmod +x /var/www/html/syspass/install_composer.sh
RUN bash /var/www/html/syspass/install_composer.sh
RUN cd /var/www/html/syspass && wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
RUN cd /var/www/html/syspass && php /var/www/html/syspass/composer.phar install --no-dev
#Apagar arquivo index do apache e redirecionar pra pasta do syspass
RUN rm /var/www/html/index.html
run echo "<?php header('Location: '. 'syspass'); exit();" >> /var/www/html/index.php