FROM ubuntu

WORKDIR /

EXPOSE 80 443

RUN apt update && apt -y install software-properties-common wget sudo
RUN apt install -y locales apache2 libapache2-mod-php php-pear php php-cgi php-cli php-common php-fpm php-gd php-json php-mysql php-readline php curl php-intl php-ldap php-xml php-mbstring
RUN service apache2 restart
RUN git clone https://github.com/nuxsmin/syspass.git /var/www/html/syspass
RUN chown www-data -R /var/www/html/syspass
COPY syspass/app/config /var/www/html/syspass/app/config
RUN chmod 750 /var/www/html/syspass/app/config /var/www/html/syspass/app/backup
RUN wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
RUN echo "<?php header('Location: syspass/);" >> /var/www/html/index.php
RUN rm /var/www/html/index.html
RUN rm -r /var/www/html/sysPass