apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syspass
  name: syspass-dp
  namespace: syspass
spec:
  replicas: 3
  selector:
    matchLabels:
      app: syspass
  template:
    metadata:
      labels:
        app: syspass
    spec:
      containers:
      - image: gcr.io/gke-cluster-322402/aleixo-syspass:ssl
        name: syspass-container
        volumeMounts:
        - name: syspass-config
          mountPath: /var/www/html/syspass/config
        - name: syspass-backup
          mountPath: /var/www/html/syspass/backup