apiVersion: v1
kind: Service
metadata:
  labels:
    app: syspass
  name: syspass-svc
  namespace: syspass
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: syspass