apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syspass
  name: syspass-dp
  namespace: syspass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syspass
  template:
    metadata:
      labels:
        app: syspass
    spec:
      containers:
      - image: syspass/syspass
        name: syspass-container